"""Initial migration

Revision ID: 953ba1510121
Revises: 
Create Date: 2024-09-17 16:39:23.974774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953ba1510121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('idx_telegram_id', 'users', ['telegram_id', 'language'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_table('playlists',
    sa.Column('spotify_playlist_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('spotify_playlist_id')
    )
    op.create_index('idx_created_at', 'playlists', ['created_at'], unique=False)
    op.create_index('idx_mood_genre', 'playlists', ['mood', 'genre'], unique=False)
    op.create_index('idx_user_id', 'playlists', ['user_id'], unique=False)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=100), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.spotify_playlist_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artist', 'playlist_tracks', ['artist'], unique=False)
    op.create_index('idx_playlist_id', 'playlist_tracks', ['playlist_id'], unique=False)
    op.create_index('idx_spotify_track_id', 'playlist_tracks', ['spotify_track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_spotify_track_id', table_name='playlist_tracks')
    op.drop_index('idx_playlist_id', table_name='playlist_tracks')
    op.drop_index('idx_artist', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index('idx_user_id', table_name='playlists')
    op.drop_index('idx_mood_genre', table_name='playlists')
    op.drop_index('idx_created_at', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
